---
- hosts: all
  tasks:

    - name: "Download Web Page"
      shell: "curl -aL https://raw.githubusercontent.com/izavalaibm/Ansible-demo/main/IBM_Page.html -o ibm_page"

    - name: "Download Web Page"
      shell: "chmod 777 ibm_page"

    - name: "Download Apache"
      yum:
        name: httpd
        state: latest

    - name: "Enable Apache"
      service:
        name: httpd
        state: started

    - name: "Download Web Page"
      shell: "ln -s ibm_page /var/www/html/"
    - name: Open port 80 for http access
      firewalld:
        service: http
        permanent: true
        state: enabled
    - name: Restart the firewalld service to load in the firewall changes
      service:
        name: firewalld
        state: restarted